version: '2'
services:
  web:
    restart: always
    build: .
    image: practicum_web:git${SHA}
    depends_on:
      - pgdb
    environment:
      - SHA
      - PORT
      - DOMAIN
    volumes:
      - server_keys:/var/keys
      - /etc/hostname:/etc/hostname_docker
      - /tmp:/tmp
    security_opt:
      - label:disable # disable SELinux for Shibboleth
    ports:
      # These stupid environment variables... You can't use the values from the section above,
      # these have to come from the Dockerfile environment, or whatever shell is running docker-compose.
      # See weirdness in some .gitlab-ci.yml build steps where we are setting env variables
      - "${PORT}:443"
      - "${HTTPPORT}:80"
  pgdb:
    restart: always
    image: postgres:9.3.24
#    environment:
#      - MONGO_DATA_DIR=/data/db
#      - MONGO_LOG_DIR=/dev/null
    volumes:
      - pgsql_home:/var/lib/pgsql
#    command: mongod --smallfiles --logpath=/dev/null # --quiet
volumes:
  server_keys:
      driver: local
  pgsql_home:
    driver: local
