version: '2'
services:
  web:
    environment:
      - SHA
      - DOMAIN
      # here we have hardcoded the container name
      # another option would been to change what port the mongos
      # are running on.
      - SHIBBOLETH_SP_ENTITYID=https://${DOMAIN}/
    volumes:
      - /webkeys/practicum:/var/keys
      - /etc/hostname:/etc/hostname_docker
      - /tmp:/tmp
    ports:
      # the 443 port is specified through an env variable via docker-compose.yml.
      # This is just to get the prod and staging a way to redirect http traffic to https
      # could have instr docker do this, too... hm...
      - "12080:80"

    #shibd:
  #  restart: always
  #  build: containers/shibd
    # This MUST be incremented whenever changes are made to the shibd image,
    # else they won't be deployed.
    # It also MUST match what is specified in .gitlab-ci.yml
  #  environment:
  #    - DOMAIN
  #    - SHIBBOLETH_SP_ENTITYID=https://${DOMAIN}/
  #    - CONTACT_EMAIL=practicum@cs.uw.edu
  #  volumes:
  #    - /webkeys/practicum:/var/keys
# HEY, YOU!  Did you just add a new service to this file?
# Don't forget to also add it to .gitlab-ci.yml
